name: footwork_chinese
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+9

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_seekbar:
    path: flutter_seekbar
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.2
  shared_preferences: ^0.5.8
  rxdart: ^0.24.1
  gradient_app_bar: ^0.1.3
  data_connection_checker: ^0.3.4
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  flutter_image_compress: ^0.7.0
  photo_view: ^0.9.2
  cached_network_image: ^2.2.0+1
  flutter_cache_manager: ^1.4.1
  webview_flutter: ^0.3.22+1
  fm_fit: ^0.0.3
  dio: ^3.0.9
  url_launcher: ^5.5.0
  flutter_webview_plugin: ^0.3.11
  uni_links: ^0.4.0
  in_app_purchase: ^0.3.4+1
  chewie: ^0.9.10
  video_player: ^0.10.11+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - lang/en.json
    - lang/zh.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Black.ttf
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/roboto/Roboto-BoldCondensed.ttf
        - asset: assets/fonts/roboto/Roboto-BoldCondensedItalic.ttf
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Condensed.ttf
        - asset: assets/fonts/roboto/Roboto-CondensedItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
